### ISSUE TITLE
Class 'PublishPress\Core\Modules\AbstractModule' not found

### ISSUE THREAD

**Issue by tschortsch** [AllediaWordPress/PublishPress#211]
When I use the Plugin directly from the GitHub repository I get the following error after enabling the plugin:
`PHP Fatal error:  Class 'PublishPress\Core\Modules\AbstractModule' not found in /var/www/content/plugins/publishpress/modules/roles/roles.php on line 44`

Plugin Version: `1.12.1`
PHP Version: `5.6.31`

Do I need to do something before the GitHub plugin works correctly (like installing dependencies, ...)?

And thanks a lot for your efforts bringing EditFlow further!

**Comment by andergmartins** [comment]
Hi @tschortsch,

You're welcome. Thanks for getting in touch.

Yes, it has some dependencies which are not in the Git repository. We use composer to track and manage them. You can't just copy the Github repo. You need to run composer to get all the dependencies and start the autoloader (the reason that class wasn't found).

You have to at least download the repository, start a session in the terminal/prompt and run the command:

```
$ composer update --no-dev
```

It will download the missed libraries and should work.

Please, could you try and let us know if it fixed the issue?

Thanks

**Comment by tschortsch** [comment]
Installing the composer dependencies helped. Thanks a lot!
