### ISSUE TITLE
Move license keys to "Add-ons" page

### ISSUE THREAD

**Issue by stevejburge** [AllediaWordPress/PublishPress#234]
We should move the license key entry to the "Add-ons" page

The "Add-ons" page will probably need a redesign with smaller images. Perhaps a horizontal listing of add-ons

**Comment by stevejburge** [comment]
Related: https://github.com/AllediaWordPress/PublishPress/issues/208

**Comment by andergmartins** [comment]
<img width="1271" alt="upstream_ _tests_ _wordpress2" src="https://user-images.githubusercontent.com/407131/43731845-31c9eb00-9986-11e8-8276-9e6fe9ae268d.png">
<img width="1268" alt="upstream_ _tests_ _wordpress" src="https://user-images.githubusercontent.com/407131/43731849-33d4067e-9986-11e8-8a63-e01d10488b8d.png">
