### ISSUE TITLE
Author Taxonomy Submenu for Custom Post Types

### ISSUE THREAD

**Issue by lichtscheu** [AllediaWordPress/PublishPress#248]
With PublishPress Multiple Authors there is a Taxonomy called "authors", for Post-Type "post" and "pages" the Plugin removes the Submenus, but not for Custom Post Types. By adding 
`'show_in_menu' => false,
 'show_in_nav_menus' => false,`
to the register_taxonomy $args the submenu never shows on any Post Type.

**Comment by andergmartins** [comment]
@lichtscheu thank you for reporting this. The show_ui was changed to true because we want to display a menu item for the taxonomy, under PublishPress menu. Adding false, we are not able to use the native taxonomy UI. I'm working in a fix for this.

**Comment by lichtscheu** [comment]
You could just get all post types and remove_submenu for them instead.

**Comment by andergmartins** [comment]
Fixed the issue. It will be released later. Feel free to reopen this issue if you have any related issue. Thanks.
