### ISSUE TITLE
Add support for Gutenberg

### ISSUE THREAD

**Issue by andergmartins** [AllediaWordPress/PublishPress#296]
- [x] Move Editorial Comments to the right sidebar
- [ ] Fix custom statuses

**Comment by andergmartins** [comment]
Note for self: Check how we can customize the status section.

https://reactjs.org/docs/hooks-intro.html#motivation
https://reactjs.org/docs/hooks-overview.html
https://reactjs.org/docs/lifting-state-up.html
https://reactjs.org/docs/render-props.html

https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/feature-custom-post-statuses.md

https://github.com/WordPress/gutenberg/issues/3144
https://github.com/WP-API/WP-API/issues/1820

**Comment by stevejburge** [comment]
Solved with January's releases
