### ISSUE TITLE
Email notification for anonymous users

### ISSUE THREAD

**Issue by andergmartins** [AllediaWordPress/PublishPress#301]
Use this chosen fork:
https://github.com/harvesthq/chosen/pull/166
https://github.com/koenpunt/chosen

<img width="378" alt="editar_post_ _test_ _wordpress" src="https://user-images.githubusercontent.com/407131/48022350-11e29600-e122-11e8-906f-1edc86db2bd1.png">

#### Support ticket 

https://secure.helpscout.net/conversation/700849220/4842?folderId=2019794

**Comment by andergmartins** [comment]
New add-on? Or available in the core for making easy to reuse in UpStream?

**Comment by stevejburge** [comment]
Let's make this part of the core

**Comment by stevejburge** [comment]
@andergmartins As we do this, let's list the workflows associated with this box https://wordpress.org/support/topic/test-publish-notify-role-selection/
