### ISSUE TITLE
Checklist can't recognize Tags, Categories, or Word Count

### ISSUE THREAD

**Issue by neddonovan13** [AllediaWordPress/PublishPress#306]
Hello! I just installed PublishPress on my site and purchased a Business license. I'm setting up the editorial checklist (a fantastic feature), but on an article with 3 categories, 20 tags, and 2,100 words, it still says I haven't met the threshold of 1 category, 1 tag, and 300 words. (There are no maximums in the settings.

How would you recommend I fix this problem?

**Comment by stevejburge** [comment]
Solved via HelpScout support ticket
