### ISSUE TITLE
PPRESS-271 ⁃ Add option to edit editorial comments

### ISSUE THREAD

**Issue by OSTraining** [AllediaWordPress/PublishPress#92]
{quote}when I add new editorial comment, there is no possibility to make updates on its. Sometime I need to update its or delete it.
{quote}

### Support ticket (private)
https://secure.helpscout.net/conversation/448979682/58237?folderId=898239

**Comment by stevejburge** [comment]
Closed in favor of https://github.com/AllediaWordPress/PublishPress/issues/277
